module {
    func.func @q10() {
        %customer_df = pandas.read_csv("/home/ajayakar/compiler-project/data/customer.csv") :
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>
        %lineitem_df = pandas.read_csv("/home/ajayakar/compiler-project/data/lineitem.csv") : 
            !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>
        %order_df = pandas.read_csv("/home/ajayakar/compiler-project/data/orders.csv") :
            !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>
        %nation_df = pandas.read_csv("/home/ajayakar/compiler-project/data/nation.csv") :
            !pandas.df<<"n_nationkey" : i32>,<"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>

        %osel_1 = pandas.filter(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            "o_orderdate" oge "1994-01-01") : !pandas.series<"osel_1": i1>
        %osel_2 = pandas.filter(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            "o_orderdate" ole "1994-04-01") : !pandas.series<"osel_2": i1>
        %osel = pandas.multiply(%osel_1: !pandas.series<"osel_1": i1>,
                %osel_2: !pandas.series<"osel_2": i1>) : 
                !pandas.series<"osel": i1>

        %lsel = pandas.filter(%lineitem_df: !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>, 
            "l_returnflag" oeq "R" ) : <"lsel": i1>

        %lineitem_filtered = pandas.filter_reduce(%lineitem_df:
            !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            %lsel: <"lsel": i1>): 
            !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>
        %orders_filtered = pandas.filter_reduce(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            %osel: <"osel": i1>) : 
            !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>

        %jn1 = pandas.join(%customer_df: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>,
            %orders_filtered: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            ["c_custkey"], ["o_custkey"]) :
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>

        %jn2 = pandas.join(%jn1: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            %lineitem_filtered: !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            ["o_orderkey"], ["l_orderkey"]) :
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>

        %jn3 = pandas.join(%jn2: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            %nation_df: !pandas.df<<"n_nationkey" : i32>,<"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>,
            ["c_nationkey"], ["n_nationkey"]) :
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>

        %l_disc = pandas.get_column(%jn3:!pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>,
            "l_discount" ) : <"l_discount": f64>

        %l_extendedprice = pandas.get_column(%jn3:!pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>,
            "l_extendedprice" ) : <"l_extendedprice": f64>

        %const1 = pandas.const_float(1.0): <"const1": f64>
        %sub = pandas.sub(%const1: <"const1": f64>, %l_disc: <"l_discount": f64>): <"sub": f64>
        %mul = pandas.multiply(%sub: <"sub": f64>, %l_extendedprice: <"l_extendedprice": f64>) :
            <"mul": f64>

        %jn3_1 = pandas.add_column(%jn3: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>,
            %mul: <"mul": f64>, "revenue") : !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>,
            <"revenue": f64>> 

        %total = pandas.groupby(%jn3_1: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>,
            <"revenue": f64>> , 
            ["c_custkey", "c_name", "c_acctbal", "c_phone", "n_name", "c_address", "c_comment"]): 
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": !pandas.group<f64>>> 
        
        %aggsum = pandas.agg_sum(%total: 
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": !pandas.group<f64>>> ,
            ["revenue"]) : 
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>> 

        %sorted = pandas.sortby(%aggsum:
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>>,
            "revenue"): 
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>>

        %limit = pandas.filter_range %sorted: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>> [0:20]
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>>
        
        %final = pandas.select(%limit: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_suppkey":!pandas.group<i32>>, <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"n_name": !pandas.string>,
            <"n_regionkey": !pandas.group<i32>>, <"n_comment": !pandas.group<!pandas.string>>,
            <"revenue": f64>>,
            ["c_custkey", "c_name", "revenue", "c_acctbal", "n_name", "c_address", "c_phone", "c_comment"]):
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>, <"n_name": !pandas.string>,
            <"revenue": f64>>
        
        pandas.print(%final: !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : !pandas.group<i32>>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, 
            <"c_comment": !pandas.string>, <"n_name": !pandas.string>,
            <"revenue": f64>>)
            
        return
    }
}