module {
    func.func @q10() {
        %customer_df = pd.read_csv("/home/ajayakar/compiler-project/data/customer.csv") :
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>
        %lineitem_df = pd.read_csv("/home/ajayakar/compiler-project/data/lineitem.csv") : 
            !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>
        %order_df = pd.read_csv("/home/ajayakar/compiler-project/data/orders.csv") :
            !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>
        %nation_df = pd.read_csv("/home/ajayakar/compiler-project/data/nation.csv") :
            !pd.df<<"n_nationkey" : i32>,<"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>

        %osel_1 = pd.filter(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            "o_orderdate" oge "1994-01-01") : !pd.ser<"osel_1": i1>
        %osel_2 = pd.filter(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            "o_orderdate" ole "1994-04-01") : !pd.ser<"osel_2": i1>
        %osel = pd.multiply(%osel_1: !pd.ser<"osel_1": i1>,
                %osel_2: !pd.ser<"osel_2": i1>) : 
                !pd.ser<"osel": i1>

        %lsel = pd.filter(%lineitem_df: !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>, 
            "l_returnflag" oeq "R" ) : <"lsel": i1>

        %lineitem_filtered = pd.filter_reduce(%lineitem_df:
            !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            %lsel: <"lsel": i1>): 
            !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>
        %orders_filtered = pd.filter_reduce(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            %osel: <"osel": i1>) : 
            !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>

        %jn1 = pd.join(%customer_df: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>,
            %orders_filtered: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            ["c_custkey"], ["o_custkey"]) :
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>

        %jn2 = pd.join(%jn1: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            %lineitem_filtered: !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            ["o_orderkey"], ["l_orderkey"]) :
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>

        %jn3 = pd.join(%jn2: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            %nation_df: !pd.df<<"n_nationkey" : i32>,<"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>,
            ["c_nationkey"], ["n_nationkey"]) :
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>

        %l_disc = pd.get_column(%jn3:!pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>,
            "l_discount" ) : <"l_discount": f64>

        %l_extendedprice = pd.get_column(%jn3:!pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>,
            "l_extendedprice" ) : <"l_extendedprice": f64>

        %const1 = pd.const_float(1.0): <"const1": f64>
        %sub = pd.sub(%const1: <"const1": f64>, %l_disc: <"l_discount": f64>): <"sub": f64>
        %mul = pd.multiply(%sub: <"sub": f64>, %l_extendedprice: <"l_extendedprice": f64>) :
            <"mul": f64>

        %jn3_1 = pd.add_column(%jn3: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>,
            %mul: <"mul": f64>, "revenue") : !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>,
            <"revenue": f64>> 

        %total = pd.groupby(%jn3_1: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>,
            <"revenue": f64>> , 
            ["c_custkey", "c_name", "c_acctbal", "c_phone", "n_name", "c_address", "c_comment"]): 
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": !pd.group<f64>>> 
        
        %aggsum = pd.agg_sum(%total: 
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": !pd.group<f64>>> ,
            ["revenue"]) : 
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>> 

        %sorted = pd.sortby(%aggsum:
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>>,
            "revenue", "asc"): 
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>>

        %limit = pd.filter_range %sorted: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>> [0:20]
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>>
        
        %final = pd.select(%limit: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_suppkey":!pd.group<i32>>, <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"n_name": !pd.string>,
            <"n_regionkey": !pd.group<i32>>, <"n_comment": !pd.group<!pd.string>>,
            <"revenue": f64>>,
            ["c_custkey", "c_name", "revenue", "c_acctbal", "n_name", "c_address", "c_phone", "c_comment"]):
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>, <"n_name": !pd.string>,
            <"revenue": f64>>
        
        pd.print(%final: !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : !pd.group<i32>>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.group<!pd.string>>, 
            <"c_comment": !pd.string>, <"n_name": !pd.string>,
            <"revenue": f64>>)
            
        return
    }
}