module {
    func.func @q3() {
        %customer_df = pd.read_csv("/home/ajayakar/compiler-project/data/customer.csv") :
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>
        %lineitem_df = pd.read_csv("/home/ajayakar/compiler-project/data/lineitem.csv") : 
            !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>
        %order_df = pd.read_csv("/home/ajayakar/compiler-project/data/orders.csv") :
            !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>
        %nation_df = pd.read_csv("/home/ajayakar/compiler-project/data/nation.csv") :
            !pd.df<<"n_nationkey" : i32>,<"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>
        %region_df = pd.read_csv("/home/ajayakar/compiler-project/data/region.csv") :
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>>
        %supplier_df = pd.read_csv("/home/ajayakar/compiler-project/data/supplier.csv") :
            !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>>

        %rsel = pd.filter(%region_df: !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>>, 
            "r_name" true "ASIA") : !pd.ser<"rsel": i1>

        %osel_1 = pd.filter(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            "o_orderdate" oge "1994-01-01") : !pd.ser<"osel_1": i1>
        %osel_2 = pd.filter(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            "o_orderdate" ole "1995-01-01") : !pd.ser<"osel_2": i1>
        %osel = pd.multiply(%osel_1: !pd.ser<"osel_1": i1>,
                %osel_2: !pd.ser<"osel_2": i1>) : 
                !pd.ser<"osel": i1>
            
        %forders = pd.filter_reduce(%order_df: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>, 
            %osel: !pd.ser<"osel": i1>) : !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>
        %fregion = pd.filter_reduce(%region_df: !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>>,
            %rsel: !pd.ser<"rsel": i1>) :
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>>

        %jn1 = pd.join(%fregion: !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>>,
            %nation_df: !pd.df<<"n_nationkey" : i32>,<"n_name": !pd.string>,
            <"n_regionkey": i32>, <"n_comment": !pd.string>>,
            ["r_regionkey"], ["n_regionkey"]) : 
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>>
        %jn2 = pd.join(%jn1:  
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>>,
            %customer_df: 
            !pd.df<<"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>,
            ["n_nationkey"], ["c_nationkey"]) :
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>

        %jn3 = pd.join(%jn2:!pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>>,
            %forders: !pd.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>, ["c_custkey"], ["o_custkey"]) : 
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>
        %jn4 = pd.join(%jn3: !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>>,
            %lineitem_df: !pd.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            ["o_orderkey"], ["l_orderkey"]):
            !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>

        %jn5 = pd.join(%supplier_df: !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>>,
            %jn4: !pd.df<<"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,
            <"n_nationkey" : i32>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            ["s_suppkey", "s_nationkey"],
            ["l_suppkey", "n_nationkey"]) : 
            !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>

        %jn5_lextendedprice = pd.get_column(%jn5:
            !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            "l_extendedprice"): !pd.ser<"l_extendedprice": f64>
        %jn5_ldiscount = pd.get_column(%jn5:
            !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            "l_discount"): !pd.ser<"l_discount": f64>

        %const_1 = pd.const_float(1.0): !pd.ser<"const_1": f64>

        %sub1 = pd.sub(%const_1: !pd.ser<"const_1": f64>,
            %jn5_ldiscount: !pd.ser<"l_discount": f64>) : 
            !pd.ser<"sub1": f64>

        %revenue = pd.multiply(%jn5_lextendedprice: !pd.ser<"l_extendedprice": f64>,
            %sub1: !pd.ser<"sub1": f64>) : 
            !pd.ser<"revenue": f64>
        
        %jn5_1 = pd.add_column(%jn5: !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>>,
            %revenue: !pd.ser<"revenue": f64>,
            "revenue") : 
            !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"revenue": f64>>

        %gb = pd.groupby(%jn5_1: !pd.df<<"s_suppkey": i32>, <"s_name" : !pd.string>,
            <"s_address": !pd.string>, <"s_nationkey": i32>,
            <"s_phone": !pd.string>, <"s_acctbal": f64>,
            <"s_comment": !pd.string>,
            <"r_regionkey": i32>, <"r_name": !pd.string>,
            <"r_comment": !pd.string>,<"n_name": !pd.string>, 
            <"n_comment": !pd.string>,
            <"c_custkey" : i32>,<"c_name" : !pd.string>,
            <"c_address" : !pd.string>,
            <"c_phone" : !pd.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pd.string>, <"c_comment": !pd.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pd.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.string>,
            <"o_clerk": !pd.string>, <"o_shippriority": i32>,
            <"o_comment": !pd.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pd.string>, 
            <"l_linestatus":!pd.string>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.string>, <"l_shipmode":!pd.string>, 
            <"comments": !pd.string>, <"revenue": f64>>,
            ["n_name"]) : 
            !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": !pd.group<f64>>>

        %agg = pd.agg_sum(%gb: !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": !pd.group<f64>>>,
            ["revenue"]): !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": f64>>

        %result_df = pd.sortby(%agg: !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": f64>>, "revenue", "asc") :
            !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": f64>>

        pd.print(%result_df: !pd.df<<"s_suppkey": !pd.group<i32>>, <"s_name" : !pd.group<!pd.string>>,
            <"s_address": !pd.group<!pd.string>>, <"s_nationkey": !pd.group<i32>>,
            <"s_phone": !pd.group<!pd.string>>, <"s_acctbal": !pd.group<f64>>,
            <"s_comment": !pd.group<!pd.string>>,
            <"r_regionkey": !pd.group<i32>>, <"r_name": !pd.group<!pd.string>>,
            <"r_comment": !pd.group<!pd.string>>,<"n_name": !pd.string>, 
            <"n_comment": !pd.group<!pd.string>>,
            <"c_custkey" : !pd.group<i32>>,<"c_name" : !pd.group<!pd.string>>,
            <"c_address" : !pd.group<!pd.string>>,
            <"c_phone" : !pd.group<!pd.string> >, <"c_acctbal": !pd.group<f64>>,
            <"c_mktsegment" : !pd.group<!pd.string>>, <"c_comment": !pd.group<!pd.string>>,
            <"o_orderkey": !pd.group<i32>>,
            <"o_orderstatus": !pd.group<!pd.string>>,<"o_totalprice": !pd.group<i32>>,
            <"o_orderdate": !pd.datetime>,<"o_orderpriority": !pd.group<!pd.string>>,
            <"o_clerk": !pd.group<!pd.string>>, <"o_shippriority": !pd.group<i32>>,
            <"o_comment": !pd.group<!pd.string>>, <"l_partkey":!pd.group<i32>>, 
            <"l_linenumber":!pd.group<i32>>,
            <"l_quantity":!pd.group<i32>>, <"l_extendedprice":!pd.group<f64>>, 
            <"l_discount":!pd.group<f64>>, <"l_tax":!pd.group<f64>>, <"l_returnflag":!pd.group<!pd.string>>, 
            <"l_linestatus":!pd.group<!pd.string>>, <"l_shipdate":!pd.datetime>, 
            <"l_commitdate":!pd.datetime>, <"l_receiptdate":!pd.datetime>, 
            <"l_shipinstruct":!pd.group<!pd.string>>, <"l_shipmode":!pd.group<!pd.string>>, 
            <"comments": !pd.group<!pd.string>>, <"revenue": f64>>)

        return
    }
}