module {
    func.func @q3() {
        %customer_df = pandas.read_csv("/home/ajayakar/compiler-project/data/customer.csv") :
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>
        %lineitem_df = pandas.read_csv("/home/ajayakar/compiler-project/data/lineitem.csv") : 
            !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>
        %order_df = pandas.read_csv("/home/ajayakar/compiler-project/data/orders.csv") :
            !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>
        %nation_df = pandas.read_csv("/home/ajayakar/compiler-project/data/nation.csv") :
            !pandas.df<<"n_nationkey" : i32>,<"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>
        %region_df = pandas.read_csv("/home/ajayakar/compiler-project/data/region.csv") :
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>>
        %supplier_df = pandas.read_csv("/home/ajayakar/compiler-project/data/supplier.csv") :
            !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>>

        %rsel = pandas.filter(%region_df: !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>>, 
            "r_name" true "ASIA") : !pandas.series<"rsel": i1>

        %osel_1 = pandas.filter(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            "o_orderdate" oge "1994-01-01") : !pandas.series<"osel_1": i1>
        %osel_2 = pandas.filter(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            "o_orderdate" ole "1995-01-01") : !pandas.series<"osel_2": i1>
        %osel = pandas.multiply(%osel_1: !pandas.series<"osel_1": i1>,
                %osel_2: !pandas.series<"osel_2": i1>) : 
                !pandas.series<"osel": i1>
            
        %forders = pandas.filter_reduce(%order_df: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>, 
            %osel: !pandas.series<"osel": i1>) : !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>
        %fregion = pandas.filter_reduce(%region_df: !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>>,
            %rsel: !pandas.series<"rsel": i1>) :
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>>

        %jn1 = pandas.join(%fregion: !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>>,
            %nation_df: !pandas.df<<"n_nationkey" : i32>,<"n_name": !pandas.string>,
            <"n_regionkey": i32>, <"n_comment": !pandas.string>>,
            ["r_regionkey"], ["n_regionkey"]) : 
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>>
        %jn2 = pandas.join(%jn1:  
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>>,
            %customer_df: 
            !pandas.df<<"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>, <"c_nationkey" : i32>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>,
            ["n_nationkey"], ["c_nationkey"]) :
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>

        %jn3 = pandas.join(%jn2:!pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>>,
            %forders: !pandas.df<<"o_orderkey": i32>,<"o_custkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>, ["c_custkey"], ["o_custkey"]) : 
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>
        %jn4 = pandas.join(%jn3: !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>>,
            %lineitem_df: !pandas.df<<"l_orderkey":i32>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            ["o_orderkey"], ["l_orderkey"]):
            !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>

        %jn5 = pandas.join(%supplier_df: !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>>,
            %jn4: !pandas.df<<"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,
            <"n_nationkey" : i32>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_suppkey":i32>, <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            ["s_suppkey", "s_nationkey"],
            ["l_suppkey", "n_nationkey"]) : 
            !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>

        %jn5_lextendedprice = pandas.get_column(%jn5:
            !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            "l_extendedprice"): !pandas.series<"l_extendedprice": f64>
        %jn5_ldiscount = pandas.get_column(%jn5:
            !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            "l_discount"): !pandas.series<"l_discount": f64>

        %const_1 = pandas.const_float(1.0): !pandas.series<"const_1": f64>

        %sub1 = pandas.sub(%const_1: !pandas.series<"const_1": f64>,
            %jn5_ldiscount: !pandas.series<"l_discount": f64>) : 
            !pandas.series<"sub1": f64>

        %revenue = pandas.multiply(%jn5_lextendedprice: !pandas.series<"l_extendedprice": f64>,
            %sub1: !pandas.series<"sub1": f64>) : 
            !pandas.series<"revenue": f64>
        
        %jn5_1 = pandas.add_column(%jn5: !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>>,
            %revenue: !pandas.series<"revenue": f64>,
            "revenue") : 
            !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"revenue": f64>>

        %gb = pandas.groupby(%jn5_1: !pandas.df<<"s_suppkey": i32>, <"s_name" : !pandas.string>,
            <"s_address": !pandas.string>, <"s_nationkey": i32>,
            <"s_phone": !pandas.string>, <"s_acctbal": f64>,
            <"s_comment": !pandas.string>,
            <"r_regionkey": i32>, <"r_name": !pandas.string>,
            <"r_comment": !pandas.string>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.string>,
            <"c_custkey" : i32>,<"c_name" : !pandas.string>,
            <"c_address" : !pandas.string>,
            <"c_phone" : !pandas.string >, <"c_acctbal": f64>,
            <"c_mktsegment" : !pandas.string>, <"c_comment": !pandas.string>,
            <"o_orderkey": i32>,
            <"o_orderstatus": !pandas.string>,<"o_totalprice": i32>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.string>,
            <"o_clerk": !pandas.string>, <"o_shippriority": i32>,
            <"o_comment": !pandas.string>, <"l_partkey":i32>, 
            <"l_linenumber":i32>,
            <"l_quantity":i32>, <"l_extendedprice":f64>, 
            <"l_discount":f64>, <"l_tax":f64>, <"l_returnflag":!pandas.string>, 
            <"l_linestatus":!pandas.string>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.string>, <"l_shipmode":!pandas.string>, 
            <"comments": !pandas.string>, <"revenue": f64>>,
            ["n_name"]) : 
            !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": !pandas.group<f64>>>

        %agg = pandas.agg_sum(%gb: !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": !pandas.group<f64>>>,
            ["revenue"]): !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": f64>>

        %result_df = pandas.sortby(%agg: !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": f64>>, "revenue") :
            !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": f64>>

        pandas.print(%result_df: !pandas.df<<"s_suppkey": !pandas.group<i32>>, <"s_name" : !pandas.group<!pandas.string>>,
            <"s_address": !pandas.group<!pandas.string>>, <"s_nationkey": !pandas.group<i32>>,
            <"s_phone": !pandas.group<!pandas.string>>, <"s_acctbal": !pandas.group<f64>>,
            <"s_comment": !pandas.group<!pandas.string>>,
            <"r_regionkey": !pandas.group<i32>>, <"r_name": !pandas.group<!pandas.string>>,
            <"r_comment": !pandas.group<!pandas.string>>,<"n_name": !pandas.string>, 
            <"n_comment": !pandas.group<!pandas.string>>,
            <"c_custkey" : !pandas.group<i32>>,<"c_name" : !pandas.group<!pandas.string>>,
            <"c_address" : !pandas.group<!pandas.string>>,
            <"c_phone" : !pandas.group<!pandas.string> >, <"c_acctbal": !pandas.group<f64>>,
            <"c_mktsegment" : !pandas.group<!pandas.string>>, <"c_comment": !pandas.group<!pandas.string>>,
            <"o_orderkey": !pandas.group<i32>>,
            <"o_orderstatus": !pandas.group<!pandas.string>>,<"o_totalprice": !pandas.group<i32>>,
            <"o_orderdate": !pandas.datetime>,<"o_orderpriority": !pandas.group<!pandas.string>>,
            <"o_clerk": !pandas.group<!pandas.string>>, <"o_shippriority": !pandas.group<i32>>,
            <"o_comment": !pandas.group<!pandas.string>>, <"l_partkey":!pandas.group<i32>>, 
            <"l_linenumber":!pandas.group<i32>>,
            <"l_quantity":!pandas.group<i32>>, <"l_extendedprice":!pandas.group<f64>>, 
            <"l_discount":!pandas.group<f64>>, <"l_tax":!pandas.group<f64>>, <"l_returnflag":!pandas.group<!pandas.string>>, 
            <"l_linestatus":!pandas.group<!pandas.string>>, <"l_shipdate":!pandas.datetime>, 
            <"l_commitdate":!pandas.datetime>, <"l_receiptdate":!pandas.datetime>, 
            <"l_shipinstruct":!pandas.group<!pandas.string>>, <"l_shipmode":!pandas.group<!pandas.string>>, 
            <"comments": !pandas.group<!pandas.string>>, <"revenue": f64>>)

        return
    }
}